### ISSUE TITLE
Faire une roadmap

### ISSUE THREAD

**Issue by Simandre** [Paris-est-Ludique/ForceOrange#2]
Afin de planifier le travail de conception pour le nouveau site de Force Orange, j'ai besoin d'établir les différentes étapes et travaux que j'aurai besoin de mener pour aboutir aux pages du site.

1. **Compréhension** • Découverte, Interview des utilisateurs 
   - [x] Préparer des interview avec les utilisateurs
      - [x] Préparer la conduite et les documents de travail
      - [x] Cibler les utilisateurs a interviewer
      - [x] Mener les interview
      - [ ] Lister les caractéristiques émergentes
   - [ ] Composer des Persona et des Cas d'usages
      - [ ] Composer quelques Personas (5 max)
      - [ ] Éprouver les personas avec l'équipe
2. **Spécifications** • Définition, Idéation et Prototypage
   - [ ] Regrouper les besoins dans une Matrice MOSCOW
   - [ ] Préparer la hiérarchie des pages du site
   - [ ] Maquetter les pages du site
   - [ ] Créer des tickets par features et les mettre au frigo. 
      - On essaie de les faire les plus petites possibles, afin d'être en kanban et pouvoir les faire avancer indépendant et de manière agile.
3. **Développement** • Prototypage et Test utilisateurs
   - [ ] …

**Comment by Simandre** [comment]
Selon le modèle du Design Thinking, le travail de conception s'articule autour de 5 étapes:

1. L'empathie
2. La définition
3. L'idéation
4. Le prototypage
5. Le Test

![Image](https://github.com/Paris-est-Ludique/ForceOrange/assets/105607989/69f9d648-db32-4561-812a-eb93e44630f4)

Dans le monde de l'UX Design, l'étape d'empathie est un processus de recherche approfondie sur l'utilisateur.

Par ailleurs, nous partons d'un site existant dont nous cherchons a apporter des améliorations.

La première étape serait donc plutôt d'interviewer des utilisateurs de FO afin d'en obtenir des retours utilisateurs et des souhaits (besoins), cela permettra d'établir les *pain points* et la liste des modifications a apporter au site.

En parallèle, je peux écrire les premières spécifications du site a partir du site existant, et définir les différentes taches et étapes a implémenter.

**Comment by Simandre** [comment]
La **recherche utilisateur** est la première chose à faire avant de se lancer dans la conception d'un produit. Elle est essentielle pour bien connaître son **utilisateur**, et cibler les bonnes personnes avec un produit qui sera adapté à leurs besoins. Si un produit ne plaît pas à sa cible, c'est que la recherche utilisateur a été mal faite, voire pas du tout…

Posez-vous la question de savoir quelle application mobile ou quel site web (quel service) vous souhaitez développer, ET pour qui.

Ce "qui", c'est le fameux **persona**. Et c'est pour cela que vous devez étudier :

1. Les **attentes** de votre utilisateur (vous devez chercher ce qu'il attend).
2. Et ses **freins cognitifs** (vous devez cherchez ce qu'il redoute/craint).
